# ============================================================
#  One-click deploy to GitHub
#  Usage:  npm run push
#  1. git add -A
#  2. git commit -m "<auto-generated message>"
#  3. git push   (Cloudflare auto-deploys on push)
# ============================================================
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

# --- 1. Collect changes -------------------------------------------------
$changes = @(git status --porcelain)
if ($changes.Count -eq 0) {
    Write-Host "[skip] Nothing to commit. Working tree is clean." -ForegroundColor Yellow
    exit 0
}

# --- 2. Build an auto-generated commit message ---------------------------
$added    = ($changes | Where-Object { $_ -match '^A|^\?\?' }).Count
$modified = ($changes | Where-Object { $_ -match '^.?M' }).Count
$deleted  = ($changes | Where-Object { $_ -match '^.?D' }).Count

$fileList = @()
foreach ($line in $changes) {
    if ($fileList.Count -ge 3) { break }
    $t = $line.Trim()
    if ($t -match '^(?:[MADRCTU?]{1,2})\s+(.+)$') { $fileList += $Matches[1] }
}
$fileStr = if ($fileList.Count -gt 0) { " [" + ($fileList -join ', ') + "]" } else { "" }

$parts = @()
if ($added -gt 0)    { $parts += "add $added" }
if ($modified -gt 0) { $parts += "update $modified" }
if ($deleted -gt 0)  { $parts += "delete $deleted" }
$action = if ($parts.Count -gt 0) { $parts -join ', ' } else { "update $($changes.Count)" }

$date    = Get-Date -Format 'yyyy-MM-dd HH:mm'
$message = "chore: $action file(s) ($($changes.Count)) on $date$fileStr"

# --- 3. Commit & push ----------------------------------------------------
Write-Host "[1/3] git add -A" -ForegroundColor Cyan
git add -A
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Host "[2/3] git commit -m `"$message`"" -ForegroundColor Cyan
git commit -m $message
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Host "[3/3] git push" -ForegroundColor Cyan
git push
if ($LASTEXITCODE -ne 0) {
    Write-Host "Push failed. Check your remote/auth, or the remote may have new commits." -ForegroundColor Red
    exit $LASTEXITCODE
}

Write-Host "Done. Pushed to GitHub, Cloudflare auto-deploy triggered." -ForegroundColor Green
